# Generated by Django 4.0.4 on 2022-06-05 09:44

from django.db import migrations, models
from models.payment import validators


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[validators.JSONSchemaValidator(limit_value={'properties': {'cash': {'maxLength': 100, 'type': 'string'}, 'cashless': {'properties': {'consignment': {'maxLength': 100, 'type': 'string'}, 'invoice': {'maxLength': 100, 'type': 'string'}}, 'type': ['object']}, 'kaspi': {'properties': {'qr': {'maxLength': 100, 'type': 'string'}, 'red': {'maxLength': 100, 'type': 'string'}, 'transfer': {'maxLength': 100, 'type': 'string'}}, 'type': ['object']}}, 'required': [], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
