# Generated by Django 4.0.4 on 2022-06-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='details',
        ),
    ]
