# Generated by Django 4.0.4 on 2022-06-13 11:33

from django.db import migrations, models
from models.payment import validators


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_type_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'maxProperties': 1, 'properties': {'cash': {'maxLength': 100, 'type': 'string'}, 'cashless': {'properties': {'consignment': {'maxLength': 100, 'type': 'string'}, 'invoice': {'maxLength': 100, 'type': 'string'}}, 'type': 'object'}, 'kaspi': {'type': 'string'}}, 'required': [], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
