# Generated by Django 4.0.4 on 2022-06-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor', '0005_contractor_version'),
        ('own', '0005_alter_own_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Актуально', 'Актуально'), ('Не актуально', 'Не актуально')], max_length=12)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiration', models.DateTimeField(verbose_name='Дата назначения')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_queue', to='contractor.contractor', verbose_name='Контагент')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_queue', to='own.own', verbose_name='Собственность')),
            ],
        ),
    ]
