# Generated by Django 4.0.5 on 2022-07-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0005_alter_tradepoint_nomenclature'),
        ('contractor', '0010_alter_contractor_name'),
        ('queue', '0002_alter_queue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='trade_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trade_point.tradepoint', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queue',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_queue', to='contractor.contractor', verbose_name='Контрагент'),
        ),
    ]
