# Generated by Django 4.0.4 on 2022-05-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
        ('own', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owns', to='contractor.contractor', verbose_name='Контрагент'),
        ),
    ]
