# Generated by Django 4.0.4 on 2022-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0002_alter_own_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='own',
            name='is_part',
            field=models.BooleanField(default=False, verbose_name='Зап.часть'),
        ),
    ]
