# Generated by Django 4.0.4 on 2022-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0003_own_is_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='own',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='own',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер'),
        ),
    ]
