# Generated by Django 4.0.4 on 2022-06-24 09:57

from django.db import migrations, models
from models.own.validators import OwnValidator


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0004_own_comment_alter_own_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[OwnValidator.int_latin_letter_validator], verbose_name='Номер'),
        ),
    ]
