# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0005_alter_own_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='own',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
