# Generated by Django 4.0.5 on 2022-07-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0006_own_is_deleted'),
        ('own', '0006_own_version'),
    ]

    operations = [
    ]
