# Generated by Django 4.0.4 on 2022-05-14 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_organization_bin_alter_organization_rnn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='BIN',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='RNN',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
