# Generated by Django 4.0.4 on 2022-05-14 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_organization_bin_alter_organization_rnn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='BIN',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,12}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='RNN',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,12}$')]),
        ),
    ]
