# Generated by Django 4.0.4 on 2022-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='service',
            field=models.ManyToManyField(related_name='organization_service', to='web.service', verbose_name='услуги'),
        ),
    ]
