# Generated by Django 4.0.4 on 2022-05-15 11:38

import apps.web.models.contractor.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='bank_requisition',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Реквизиты банковского счёта'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='trust_person',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[apps.web.models.contractor.validators.JSONSchemaValidator(limit_value={'properties': {'comment': {'maxLength': 150, 'type': 'string'}, 'name': {'maxLength': 100, 'type': 'string'}}, 'required': ['name'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
