# Generated by Django 4.0.4 on 2022-05-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_nomenclature_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.nomenclature', verbose_name='Номенклатура')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.organization', verbose_name='Организация')),
            ],
        ),
    ]
