# Generated by Django 4.0.4 on 2022-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_contractor_bank_requisition_and_more'),
        ('web', '0011_tradepoint'),
    ]

    operations = [
    ]
