# Generated by Django 4.0.4 on 2022-05-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_merge_20220515_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатуры'},
        ),
    ]
