# Generated by Django 4.0.4 on 2022-05-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_nomenclature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='tradepoint',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
