# Generated by Django 4.0.4 on 2022-05-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_contractor_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
