# Generated by Django 4.0.5 on 2022-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tradepoint_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_uuid',
            field=models.UUIDField(editable=False, verbose_name='Отчет'),
        ),
    ]
