# Generated by Django 4.0.4 on 2022-05-18 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Диагностика', 'Диагностика'), ('Техническое обслуживание', 'Техническое обслуживание'), ('Текущий ремонт двигателя', 'Текущий ремонт двигателя'), ('Токарные, фрезерные, шлифовочные и расточные работы', 'Токарные, фрезерные, шлифовочные и расточные работы'), ('Система питания', 'Система питания'), ('Система выпуска газов', 'Система выпуска газов'), ('Система охлаждения', 'Система охлаждения'), ('Сцепление', 'Сцепление'), ('Коробка передач', 'Коробка передач'), ('Карданный вал', 'Карданный вал'), ('Задний мост', 'Задний мост'), ('Подвеска', 'Подвеска'), ('Колеса-ступицы', 'Колеса-ступицы'), ('Рулевое управление', 'Рулевое управление'), ('Тормозная система', 'Тормозная система'), ('Электрооборудование', 'Электрооборудование'), ('Двери', 'Двери'), ('Отопитель', 'Отопитель')], max_length=100, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('mark', models.CharField(choices=[('Газель', 'Газель'), ('Валдай Дв Д245/Cummin s 3.8 2.8', 'Валдай Дв Д245/Cummin s 3.8 2.8')], max_length=100, verbose_name='Марка')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclature_services', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
    ]
