# Generated by Django 4.0.4 on 2022-05-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_remove_nomenclature_service'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nomenclature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclature_services', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
            preserve_default=False,
        ),
    ]
