# Generated by Django 4.0.4 on 2022-06-20 08:13

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepoint',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
