# Generated by Django 4.0.4 on 2022-06-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_alter_nomenclature_name'),
        ('trade_point', '0002_tradepoint_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepoint',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_points', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
