# Generated by Django 4.0.4 on 2022-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_alter_nomenclature_name'),
        ('trade_point', '0003_alter_tradepoint_nomenclature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepoint',
            name='nomenclature',
        ),
        migrations.AddField(
            model_name='tradepoint',
            name='nomenclature',
            field=models.ManyToManyField(blank=True, related_name='trade_points', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
