# Generated by Django 4.0.4 on 2022-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_alter_nomenclature_name'),
        ('trade_point', '0004_remove_tradepoint_nomenclature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepoint',
            name='nomenclature',
            field=models.ManyToManyField(related_name='trade_points', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
