# Generated by Django 4.0.4 on 2022-06-14 14:07

from django.db import migrations, models
from models.contractor import validators


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_remove_contractor_bank_requisition_contractor_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='trust_person',
            field=models.JSONField(
                blank=True, default=dict, null=True,
                validators=[validators.JSONSchemaValidator(
                    limit_value={
                        'additionalProperties': False, 'properties': {
                            'comment': {'maxLength': 150, 'type': 'string'},
                            'name': {'maxLength': 100, 'type': 'string'}},
                        'required': ['name'], 'schema': 'http://json-schema.org/draft-07/schema#',
                        'type': 'object'})]),
        ),
    ]
