# Generated by Django 4.0.4 on 2022-06-27 15:55

import django.core.validators
from django.db import migrations, models
import localflavor.generic.models
from models.contractor import validators


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_contractor_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='BIC',
            field=localflavor.generic.models.BICField(blank=True, max_length=100, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='IIN_or_BIN',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$'), validators.validate_iin], verbose_name='ИИН/БИН'),
        ),
    ]
