# Generated by Django 4.0.4 on 2022-06-27 18:05

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0006_alter_contractor_bic_alter_contractor_iin_or_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='IIC',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=100, null=True, use_nordea_extensions=False, verbose_name='ИИК'),
        ),
    ]
