# Generated by Django 4.0.4 on 2022-06-28 05:39

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_alter_contractor_iic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='BIC',
            field=localflavor.generic.models.BICField(blank=True, max_length=100, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='IIC',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=100, null=True, use_nordea_extensions=False, verbose_name='ИИК'),
        ),
    ]
