# Generated by Django 4.0.5 on 2022-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0010_alter_contractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='BIC',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='IIC',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИИК'),
        ),
    ]
