# Generated by Django 4.0.4 on 2022-05-31 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor', '0003_remove_contractor_bank_requisition_contractor_bic_and_more'),
        ('own', '0002_alter_own_contractor'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('in_process', 'В работе'), ('completed', 'Завершен')], max_length=100, verbose_name='Статус')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contractor.contractor', verbose_name='Контрагент')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_orders', to='own.own', verbose_name='Собственность')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='payment.payment', verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
            },
        ),
    ]
