# Generated by Django 4.0.4 on 2022-06-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branch_orders', to='trade_point.tradepoint', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
