# Generated by Django 4.0.4 on 2022-06-08 09:16

from django.db import migrations, models
from models.order import validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jobs',
            field=models.JSONField(default=[], validators=[validators.JSONSchemaValidator(limit_value={'items': {'properties': {'Гарантия': {'default': False, 'type': 'boolean'}, 'Заказ': {'minimum': 1, 'type': 'integer'}, 'Мастера': {'items': {'type': 'number'}, 'type': 'array'}, 'Название услуги': {'maxLength': 500, 'type': 'string'}, 'Цена услуги': {'minimum': 1, 'type': 'integer'}}, 'required': ['Заказ', 'Название', 'Марка', 'Цена'], 'type': 'object'}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})], verbose_name='Работы'),
            preserve_default=False,
        ),
    ]
