# Generated by Django 4.0.4 on 2022-06-11 08:30

import django.core.validators
from django.db import migrations, models
from models.order import validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полная сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_for_pay',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма с гарантиями'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='jobs',
            field=models.JSONField(validators=[validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': {'maximum': 10000, 'minimum': 0, 'type': 'integer'}, 'maxProperties': 5, 'properties': {'Гарантия': {'default': False, 'type': 'boolean'}, 'Мастера': {'items': {'type': 'number'}, 'type': 'array'}, 'Название услуги': {'maxLength': 500, 'type': 'string'}, 'Цена услуги': {'minimum': 1, 'type': 'integer'}}, 'required': ['Название услуги', 'Цена услуги', 'Гарантия', 'Мастера'], 'type': 'object'}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})], verbose_name='Работы'),
        ),
    ]
