# Generated by Django 4.0.4 on 2022-06-16 11:28

from django.db import migrations, models
from models.order import validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jobs',
            field=models.JSONField(validators=[validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': {'maximum': 10000, 'minimum': 0, 'type': 'integer'}, 'maxProperties': 7, 'properties': {'Гарантия': {'default': False, 'type': 'boolean'}, 'Категория услуги': {'maxLength': 500, 'type': 'string'}, 'Марка услуги': {'maxLength': 500, 'type': 'string'}, 'Мастера': {'items': {'additionalProperties': False, 'properties': {'ИИН': {'type': 'integer'}, 'Наименование': {'maxLength': 500, 'type': 'string'}}, 'required': ['Наименование', 'ИИН'], 'type': 'object'}, 'type': 'array'}, 'Название услуги': {'maxLength': 500, 'type': 'string'}, 'Цена услуги': {'minimum': 1, 'type': 'integer'}}, 'required': ['Название услуги', 'Категория услуги', 'Марка услуги', 'Цена услуги', 'Гарантия', 'Мастера'], 'type': 'object'}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})], verbose_name='Работы'),
        ),
    ]
