# Generated by Django 4.0.4 on 2022-05-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='service',
        ),
    ]
