# Generated by Django 4.0.4 on 2022-05-19 15:46

from django.db import migrations, models
from models.nomenclature import validators


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='services',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[validators.JSONSchemaValidator(limit_value={'properties': {'category': {'maxLength': 150, 'type': 'string'}, 'mark': {'maxLength': 150, 'type': 'string'}, 'name': {'maxLength': 150, 'type': 'string'}, 'note': {'maxLength': 300, 'type': 'string'}, 'price': {'minimum': 1, 'type': 'integer'}}, 'required': ['category', 'name', 'note', 'mark', 'price'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
