# Generated by Django 4.0.4 on 2022-06-27 14:43

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_alter_nomenclature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
