# Generated by Django 4.0.4 on 2022-05-28 06:11

import django.core.validators
from django.db import migrations, models
from models.employee import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('MASTER', 'MASTER'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('MANAGER', 'MANAGER')], max_length=150)),
                ('IIN', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$')], verbose_name='ИИН')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('birthdate', models.DateField()),
                ('tradepoints', models.JSONField(blank=True, default=list, null=True, validators=[validators.JSONSchemaValidator(limit_value={'items': {'properties': {'id': {'minimum': 0, 'type': 'number'}}, 'required': ['id'], 'type': 'object'}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})])),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
