# Generated by Django 4.0.4 on 2022-05-29 12:48

from django.db import migrations, models
from models.employee import validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_id_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tradepoints',
            field=models.JSONField(blank=True, default=list, null=True, validators=[validators.JSONSchemaValidator(limit_value={'properties': {'id': {'minimum': 1, 'type': 'number'}}, 'required': ['id'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
