# Generated by Django 4.0.4 on 2022-06-21 10:51

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
