# Generated by Django 4.0.4 on 2022-05-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_tradepoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Мастер', 'Мастер'), ('Управляющий', 'Управляющий'), ('Менеджер', 'Менеджер')], max_length=150),
        ),
    ]
