# Generated by Django 4.0.4 on 2022-05-31 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0001_initial'),
        ('employee', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tradepoints',
        ),
        migrations.AddField(
            model_name='employee',
            name='tradepoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tradepoint_employee', to='trade_point.tradepoint', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
