# Generated by Django 4.0.4 on 2022-06-26 19:42

from django.db import migrations, models
from models.employee import validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='IIN',
            field=models.CharField(max_length=12, unique=True, validators=[validators.validate_iin], verbose_name='ИИН'),
        ),
    ]
