# Generated by Django 4.0.4 on 2022-06-28 06:32

from django.db import migrations, models
from models.employee import validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, validators=[validators.latin_validate, validators.number_validate], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=100, validators=[validators.len_phone_validate], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=50, validators=[validators.latin_surname_validate, validators.number_surname_validate], verbose_name='Фамилия'),
        ),
    ]
